apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: test
spec:
  selector:
    app: app1
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: test
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: python-debugging-app1:v0.1.0
        imagePullPolicy: Never
        env:
          - name: API
            value: "http://app2:5000"
          - name: DEBUGPY_LOG_DIR
            value: "/app/logs"
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: test
spec:
  selector:
    app: app2
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: test
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: python-debugging-app2:v0.1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "100m"
