version: '3.9'

services:
  scalene:
    image: scalene_test
    stdin_open: true
    tty: true
    container_name: scalene
    volumes:
      - $PWD/app:/app
    networks:
      - scalene
    command:
      - bash
    ports:
      - "8080:8080"

networks:
  scalene:
    driver: bridge
