version: '3.9'

services:
  pypy_3.9_slim:
    image: pypy_3.9_slim
    stdin_open: true
    tty: true
    container_name: pypy_3.9_slim
    volumes:
      - $PWD/app:/app
    networks:
      - pypy_3.9_slim
    command:
      - "bash"
    # ports:
    #   - "8080:8080"

networks:
  pypy_3.9_slim:
    driver: bridge
